name: dherkin2
version: 1.0.1+1
authors:
- Danil Kornishev <danil.kornishev@gmail.com>
- Florian Huonder <florian.huonder@prolutions.ch>
- Sacha Dolski <sacha.dolski@prolutions.ch>
description: Gherkin/Cucumber implementation in dart (migrated to Dart2's async/await semantics).
homepage: https://github.com/prolutionsGmbH/dherkin
dependencies:
  logging: ^0.11.3+2
  args: ^1.5.0
  ansicolor: ^1.0.2
environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  build_runner: ^0.10.2
